name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: .  #Change to your Maven project directory
      run: mvn -B package --file pom.xml
       # Krijimi i imazhit dhe publikimi ne dokerbuh
    - name: Krijo imazh dhe bej push ne dockerhub
      uses: docker/build-push-action@v2  
      with:    
       context: .
       username: ${{secrets.DOCKER_HUB_USERNAM}}
       password:  ${{secrets.DOCKER_HUB_PASSWORD}}
       repository:  sselmanaj/cloud-apps-mpl 
       tags: cloudappdevelopment-v${{github.run_number}}
